"docker-compose.yaml" 13L, 296B
version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
